### PR TITLE
Add Prior Art

### PR DESCRIPTION
**Pull request by scottrobertwhittaker**
Hi Max! Sorry for the long delay getting back to you on this - here are some notes on the prior art.

I think the biggest problem is that we are going to have to also make angle brackets a kind of comment too.  As I understand, this project is really intended to let us avoid slow parsing and rewriting of typed files into `.js` files: the typed code will magically parse as JS, ignoring our annotations.  But many (most?) TypeScript files will have generics. If our syntax only allows colon-comment removal, we'll forego our performance improvement when many `.ts` files still need to be rewritten.  Allowing angle brackets in the appropriate contexts (in particular, between function name and parenthesis) should help.

Treating angle brackets as comments also helps us figure out when the post-colon `Annotation` production is complete: I think we should just be able to say that the part after the colon must parse as an expression. This is how the Python type annotation grammar works according to PEP 3107. Are there TypeScript type annotations that wouldn't work with this?

Even with angle brackets, there will still be cases where rewriting a file will be necessary.  First, as you mentioned, we say nothing about `type` and `interface`.  Second, Flow unfortunately has at least a couple syntaxes - for "maybe types" and "exact object types" - which are not grammatical JavaScript.  I don't think there is much we can do about either of these specific problems without making this proposal "know too much" about the syntax of TypeScript and Flow.

It may be worth gathering some data about what proportion of files in representative TypeScript and Flow codebases would parse or not with our syntax extension. Flow in particular has enough grammatical idiosyncrasy that I'd be worried that even this proposal would be insufficient to get files parsing.

Finally, I'm also not sure how useful the references to Closure / JSDoc / Sorbet are, since they work in an entirely different way to what we'd be proposing here.

Let me know what you think -- thanks!

### CODE REVIEW

**Review by mheiber — APPROVED** [review]

**Comment by mheiber** [comment]
Hi Scott,

Really sorry to have taken so long to respond!! I have not been good about keeping up with GitHub notifications.

I merged in the prior art, I think it's broad and helpful!

Re `type`/`interface`:

What do you think of not supporting all TS and Flow syntax? For example, if we require `type`/`interface`/etc. to be in block comments, that might not be too bad. It would require changes to TS and Flow, but we could see if we can get buy-in from the Flow and TS teams.

Re angle brackets: I think specifying the syntax along these lines might work:

> The idea is that we require matching delimiter pairs

ACE ::= ":" ACEBlock
ACEBlock ::= (Identifier | ACEBracketPhrase | AceParenthesisPhrase | AceAngleBracketPhrase )+
ACEAngleBracketPhrase ::= "<" ACEBlock ">"
ACEBracketPhrase ::= "[" ACEBlock "]"
ACEParenthesisPhrase ::= "(" ACEBlock ")"

What do you think?

**Comment by scottrobertwhittaker** [comment]
Thanks Max! I'm the slow one now :)

Requiring `type`/`interface` to be in comments sounds good to me -- I'll push a commit mentioning this.

Matching delimiter pairs idea sounds good -- we'll just be bracket-counting. I do think we'll need to have something more arbitrary than `Identifier` in the definition of `ACEBlock` to deal with idiosyncrasies like `{| bar: number |}` in Flow. What's the best way to play around with grammar changes like this -- are we at the point where it makes sense to start hacking together a Babel plugin or something? Thanks!

**Comment by mheiber** [comment]
Hey Scott, I'm going to be the slow one again, as I'm on vacay.

Good point about the Flow `{|` syntax: perhaps `{|`+`|}` could be considered a delimiter pair.

I'm not sure if the Babel parser is pluggable enough, but it's worth a try.

When I get back, I might look into whether there is a way to experiment with a parser generator. I think I found a ES2015 antlr grammer, but haven't tried it yet: https://github.com/antlr/grammars-v4/tree/master/javascript

Re making a Babel plugin: I'm not sure if the Babel parser is pluggable enough for this to be a plugin, but it's worth a shot.

**Comment by scottrobertwhittaker** [comment]
Thanks Max! I'll have a peek around and let you know what I find.

**Pull request merged**
